# Lab3: Create a pie chart to illustrate the distribution of a company's revenue
# across its various business segments. You have collected data on the revenue
# generated by each segment, such as Product A, Product B, Services, and
# Licensing. Share your conclusion/analysis.
# Input:
import matplotlib.pyplot as plt

segments = ['Product A', 'Product B', 'Services', 'Licensing']
revenue_percentages = [45, 25, 15, 15]

plt.pie(revenue_percentages,labels=segments,startangle=130,autopct="%1.1f%%")
plt.title("Distribution of Company Revenue by Business Segment ")

plt.show()
